#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Resultado; end

class Resultado
  include ::Thrift::Struct, ::Thrift::Struct_Union
  RESULTADOOPERACION = 1
  MENSAJE = 2

  FIELDS = {
    RESULTADOOPERACION => {:type => ::Thrift::Types::I32, :name => 'resultadoOperacion'},
    MENSAJE => {:type => ::Thrift::Types::STRING, :name => 'mensaje'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

